name: loterias
version: "1.0.0"
config-version: 2

profile: loterias

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  loterias:
    +grants:
      select: ["metabase"]
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

on-run-end:
  - "{% for schema in schemas %}grant usage on schema {{ schema }} to metabase;{% endfor %}"
